# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R5PxPNGSISqOpo2JVC3raPNmj14MZJW2
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("train.csv")
# CREATE datetime and year FIRST
df["datetime"] = pd.to_datetime(df["datetime"])
df["year"] = df["datetime"].dt.year
df["month"] = df["datetime"].dt.month
df["hour"] = df["datetime"].dt.hour


st.title("Bike Rental Dashboard")

# ---- INTERACTIVE DROPDOWN ----
selected_year = st.selectbox(
    "Select Year",
    sorted(df["year"].unique())
)

# Filter data based on selected year
filtered_df = df[df["year"] == selected_year]


df.head()

df["datetime"] = pd.to_datetime(df["datetime"])
df["datetime"].head()

print(df.dtypes)
print("Number of rows:", len(df))
print(df.isna().sum())

df["year"] = df["datetime"].dt.year
df["month"] = df["datetime"].dt.month
df["day_of_week"] = df["datetime"].dt.day_name()
df["hour"] = df["datetime"].dt.hour

df[["datetime", "year", "month", "day_of_week", "hour"]].head()

season_map = {1: "spring", 2: "summer", 3: "fall", 4: "winter"}
df["season_name"] = df["season"].map(season_map)

df[["season", "season_name"]].drop_duplicates()

df.groupby("season_name")["count"].mean()

df.groupby("year")[["casual", "registered"]].sum()

df.groupby("workingday")[["registered", "casual"]].mean()



monthly = df.groupby(["year", "month"])["count"].sum()
monthly

df.groupby("weather")["count"].mean()

df.corr(numeric_only=True)["count"].sort_values(ascending=False)

bins = [0, 6, 12, 18, 24]
labels = ["night", "morning", "afternoon", "evening"]

df["day_period"] = pd.cut(df["hour"], bins=bins, labels=labels, right=False)

df[["hour", "day_period"]].head(24)

pivot = pd.pivot_table(
    df,
    index="day_period",
    columns="workingday",
    values="count",
    aggfunc="mean"
)

pivot

#ASSIGNMENT 2

#STEP 1
import matplotlib.pyplot as plt
numerical_cols = df.select_dtypes(include="number").columns

df[numerical_cols].hist(figsize=(15,10))
plt.show()

#STEP 2
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(15,6))
sns.boxplot(data=df[numerical_cols])
plt.xticks(rotation=45)
plt.show()

#STEP 3
mean_working = df.groupby("workingday")["count"].mean()

mean_working.plot(kind="bar")
plt.xlabel("Working Day (0 = No, 1 = Yes)")
plt.ylabel("Mean Rentals")
plt.title("Mean Bike Rentals: Working vs Non-working Days")
plt.show()

#STEP 4
import pandas as pd

df = pd.read_csv("train.csv")
df["datetime"] = pd.to_datetime(df["datetime"])

import matplotlib.pyplot as plt

# create month column
df["month"] = df["datetime"].dt.month

# calculate mean rentals per month (both years)
monthly_mean = df.groupby("month")["count"].mean()

# plot
monthly_mean.plot(marker="o")
plt.xlabel("Month")
plt.ylabel("Mean Hourly Rentals")
plt.title("Mean Hourly Bike Rentals by Month (Both Years Combined)")
plt.xticks(range(1, 13))
plt.show()

#STEP 5
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("train.csv")
df["datetime"] = pd.to_datetime(df["datetime"])

df["year"] = df["datetime"].dt.year
df["month"] = df["datetime"].dt.month

monthly_year_mean = df.groupby(["year", "month"])["count"].mean().reset_index()
fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)
for i, year in enumerate(sorted(monthly_year_mean["year"].unique())):
    temp = monthly_year_mean[monthly_year_mean["year"] == year]
    axes[i].plot(temp["month"], temp["count"], marker="o")
    axes[i].set_title(f"Mean Rentals by Month - {year}")
    axes[i].set_xlabel("Month")
    axes[i].set_xticks(range(1, 13))

axes[0].set_ylabel("Mean Hourly Rentals (count)")
plt.tight_layout()
plt.show()

#STEP 6
sns.barplot(
    data=df,
    x="weather",
    y="count",
    errorbar=("ci", 95)
)

plt.xlabel("Weather Category")
plt.ylabel("Mean Hourly Rentals")
plt.title("Mean Hourly Bike Rentals by Weather (95% Confidence Interval)")
plt.show()

#STEP 7
df["datetime"] = pd.to_datetime(df["datetime"])
df["hour"] = df["datetime"].dt.hour
import matplotlib.pyplot as plt

hourly_mean = df.groupby("hour")["count"].mean()

hourly_mean.plot()
plt.xlabel("Hour of Day")
plt.ylabel("Mean Hourly Rentals")
plt.title("Mean Hourly Bike Rentals by Hour of Day")
plt.xticks(range(0, 24))
plt.show()

#STEP 8
df["datetime"] = pd.to_datetime(df["datetime"])
df["hour"] = df["datetime"].dt.hour
df["day_of_week"] = df["datetime"].dt.day_name()
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

sns.lineplot(
    x="hour",
    y="count",
    hue="day_of_week",
    data=df
)

plt.xlabel("Hour of Day")
plt.ylabel("Mean Hourly Rentals")
plt.title("Hourly Bike Rentals by Day of the Week")
plt.xticks(range(0, 24))
plt.legend(title="Day of Week", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.show()

#STEP 9
df["datetime"] = pd.to_datetime(df["datetime"])
df["hour"] = df["datetime"].dt.hour

season_map = {1: "spring", 2: "summer", 3: "fall", 4: "winter"}
df["season_name"] = df["season"].map(season_map)
import seaborn as sns
import matplotlib.pyplot as plt

g = sns.FacetGrid(
    df,
    col="season_name",
    col_wrap=2,
    height=4,
    aspect=1.2
)

g.map(sns.lineplot, "hour", "count")

g.set_axis_labels("Hour of Day", "Mean Hourly Rentals")
g.set_titles("{col_name}")
plt.show()

#STEP 10
df["datetime"] = pd.to_datetime(df["datetime"])

# hour column
df["hour"] = df["datetime"].dt.hour

# day_period column (same as Assignment 1)
bins = [0, 6, 12, 18, 24]
labels = ["night", "morning", "afternoon", "evening"]
df["day_period"] = pd.cut(df["hour"], bins=bins, labels=labels, right=False)

#step 10
import seaborn as sns
import matplotlib.pyplot as plt

sns.barplot(
    data=df,
    x="day_period",
    y="count",
    hue="workingday",
    errorbar=("ci", 95)
)

plt.xlabel("Period of the Day")
plt.ylabel("Mean Hourly Rentals")
plt.title("Mean Rentals by Day Period (Working vs Non-working Days)")
plt.legend(title="Working Day (0 = No, 1 = Yes)")
plt.show()

#STEP 11
import seaborn as sns
import matplotlib.pyplot as plt
# calculate correlation matrix (numeric columns only)
corr_matrix = df.corr(numeric_only=True)

# plot heatmap
plt.figure(figsize=(10,8))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap of Numerical Variables")
plt.show()
st.subheader("Mean Rentals by Hour (Interactive)")

fig, ax = plt.subplots()
filtered_df.groupby("hour")["count"].mean().plot(ax=ax)
ax.set_xlabel("Hour")
ax.set_ylabel("Mean Rentals")
ax.set_title(f"Year: {selected_year}")
st.write("Change the year from the dropdown to see the graph update.")


st.pyplot(fig)

st.subheader("Mean Rentals by Month")

fig2, ax2 = plt.subplots()
df.groupby("month")["count"].mean().plot(marker="o", ax=ax2)
ax2.set_xlabel("Month")
ax2.set_ylabel("Mean Rentals")

st.pyplot(fig2)
st.subheader("Mean Rentals by Weather")

fig3, ax3 = plt.subplots()
sns.barplot(data=df, x="weather", y="count", errorbar=("ci", 95), ax=ax3)
ax3.set_xlabel("Weather")
ax3.set_ylabel("Mean Rentals")

st.pyplot(fig3)
st.subheader("Day Period vs Working Day")

fig4, ax4 = plt.subplots()
sns.barplot(
    data=df,
    x="day_period",
    y="count",
    hue="workingday",
    errorbar=("ci", 95),
    ax=ax4
)
ax4.set_xlabel("Day Period")
ax4.set_ylabel("Mean Rentals")

st.pyplot(fig4)
st.subheader("Correlation Heatmap")

fig5, ax5 = plt.subplots(figsize=(8, 6))
sns.heatmap(
    df.corr(numeric_only=True),
    cmap="coolwarm",
    annot=False,
    ax=ax5
)
st.pyplot(fig5)


